#ifndef DCC_SUGAR_LISTENERS_DECORATED_H
#define DCC_SUGAR_LISTENERS_DECORATED_H

#include <dcc/sugar/listeners/base_routes.h>
#include <dcc/sugar/listeners/typed_commands.h>
#include <dcc/sugar/listeners/typed_components.h>

#define DCC_LISTEN_DECORATED_SLASH(handler_) \
    DCC_LISTEN_SLASH_ROUTE(DCC_ROUTE(handler_))
#define DCC_LISTEN_SLASH_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_SLASH(handler_)
#define DCC_LISTEN_DECORATED_COMMAND(handler_) \
    DCC_LISTEN_DECORATED_SLASH(handler_)
#define DCC_LISTEN_COMMAND_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_COMMAND(handler_)

#define DCC_LISTEN_DECORATED_SUBCOMMAND(handler_) \
    DCC_LISTEN_SUBCOMMAND_ROUTE(DCC_ROUTE(handler_))
#define DCC_LISTEN_SUBCOMMAND_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_SUBCOMMAND(handler_)

#define DCC_LISTEN_DECORATED_AUTOCOMPLETE(handler_) \
    DCC_LISTEN_AUTOCOMPLETE_ROUTE(DCC_ROUTE(handler_))
#define DCC_LISTEN_AUTOCOMPLETE_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_AUTOCOMPLETE(handler_)

#define DCC_LISTEN_DECORATED_CONTEXT_MENU(handler_) \
    DCC_LISTEN_CONTEXT_MENU_ROUTE(DCC_ROUTE(handler_))
#define DCC_LISTEN_CONTEXT_MENU_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_CONTEXT_MENU(handler_)
#define DCC_LISTEN_DECORATED_USER_CONTEXT_MENU(handler_) \
    DCC_LISTEN_DECORATED_CONTEXT_MENU(handler_)
#define DCC_LISTEN_USER_CONTEXT_MENU_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_USER_CONTEXT_MENU(handler_)
#define DCC_LISTEN_DECORATED_MESSAGE_CONTEXT_MENU(handler_) \
    DCC_LISTEN_DECORATED_CONTEXT_MENU(handler_)
#define DCC_LISTEN_MESSAGE_CONTEXT_MENU_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_MESSAGE_CONTEXT_MENU(handler_)

#define DCC_LISTEN_DECORATED_COMPONENT(handler_) \
    DCC_LISTEN_COMPONENT_ROUTE(DCC_ROUTE(handler_))
#define DCC_LISTEN_COMPONENT_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_COMPONENT(handler_)
#define DCC_LISTEN_DECORATED_BUTTON(handler_) \
    DCC_LISTEN_DECORATED_COMPONENT(handler_)
#define DCC_LISTEN_BUTTON_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_BUTTON(handler_)
#define DCC_LISTEN_DECORATED_SELECT(handler_) \
    DCC_LISTEN_DECORATED_COMPONENT(handler_)
#define DCC_LISTEN_SELECT_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_SELECT(handler_)
#define DCC_LISTEN_DECORATED_MODAL(handler_) \
    DCC_LISTEN_DECORATED_COMPONENT(handler_)
#define DCC_LISTEN_MODAL_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_MODAL(handler_)

#define DCC_LISTEN_DECORATED_EVENT(handler_) \
    DCC_LISTEN_EVENT_ROUTE(DCC_ROUTE(handler_))
#define DCC_LISTEN_EVENT_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_EVENT(handler_)
#define DCC_LISTEN_DECORATED_READY(handler_) \
    DCC_LISTEN_DECORATED_EVENT(handler_)
#define DCC_LISTEN_READY_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_READY(handler_)

#define DCC_LISTEN_DECORATED_MESSAGE_COMMAND(handler_) \
    DCC_LISTEN_MESSAGE_COMMAND_ROUTE(DCC_ROUTE(handler_))
#define DCC_LISTEN_MESSAGE_COMMAND_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_MESSAGE_COMMAND(handler_)
#define DCC_LISTEN_DECORATED_PREFIX_COMMAND(handler_) \
    DCC_LISTEN_DECORATED_MESSAGE_COMMAND(handler_)
#define DCC_LISTEN_PREFIX_COMMAND_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_PREFIX_COMMAND(handler_)

#define DCC_LISTEN_DECORATED_TASK(handler_) \
    DCC_LISTEN_TASK_ROUTE(DCC_ROUTE(handler_))
#define DCC_LISTEN_TASK_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_TASK(handler_)

#define DCC_LISTEN_DECORATED_TYPED_SLASH(handler_) \
    DCC_LISTEN_TYPED_SLASH(DCC_TYPED_ROUTE(handler_))
#define DCC_LISTEN_TYPED_SLASH_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_TYPED_SLASH(handler_)
#define DCC_LISTEN_DECORATED_TYPED_COMMAND(handler_) \
    DCC_LISTEN_DECORATED_TYPED_SLASH(handler_)
#define DCC_LISTEN_TYPED_COMMAND_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_TYPED_COMMAND(handler_)

#define DCC_LISTEN_DECORATED_TYPED_SUBCOMMAND(handler_) \
    DCC_LISTEN_TYPED_SUBCOMMAND(DCC_TYPED_ROUTE(handler_))
#define DCC_LISTEN_TYPED_SUBCOMMAND_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_TYPED_SUBCOMMAND(handler_)

#define DCC_LISTEN_DECORATED_TYPED_AUTOCOMPLETE(handler_) \
    DCC_LISTEN_TYPED_AUTOCOMPLETE(DCC_TYPED_ROUTE(handler_))
#define DCC_LISTEN_TYPED_AUTOCOMPLETE_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_TYPED_AUTOCOMPLETE(handler_)

#define DCC_LISTEN_DECORATED_TYPED_MODAL(handler_) \
    DCC_LISTEN_TYPED_MODAL(DCC_TYPED_ROUTE(handler_))
#define DCC_LISTEN_TYPED_MODAL_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_TYPED_MODAL(handler_)

#define DCC_LISTEN_DECORATED_TYPED_BUTTON(handler_) \
    DCC_LISTEN_TYPED_BUTTON(DCC_TYPED_ROUTE(handler_))
#define DCC_LISTEN_TYPED_BUTTON_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_TYPED_BUTTON(handler_)

#define DCC_LISTEN_DECORATED_TYPED_SELECT(handler_) \
    DCC_LISTEN_TYPED_SELECT(DCC_TYPED_ROUTE(handler_))
#define DCC_LISTEN_TYPED_SELECT_DECORATED(handler_) \
    DCC_LISTEN_DECORATED_TYPED_SELECT(handler_)


#endif
