#ifndef DCC_OBJECTS_GATEWAY_EVENT_DATA_H
#define DCC_OBJECTS_GATEWAY_EVENT_DATA_H

/* Normalized gateway event data shared by multiple dispatch payloads. */

#include <dcc/objects/gateway/activity.h>
#include <dcc/objects/gateway_updates.h>

typedef struct dcc_gateway_event_data {
    dcc_snowflake_t id;
    dcc_snowflake_t guild_id;
    dcc_snowflake_t channel_id;
    dcc_snowflake_t user_id;
    dcc_user_t user;
    dcc_snowflake_t message_id;
    dcc_snowflake_t role_id;
    dcc_snowflake_t parent_id;
    dcc_snowflake_t target_id;
    dcc_snowflake_t application_id;
    dcc_snowflake_t scheduled_event_id;
    dcc_snowflake_t sku_id;
    dcc_snowflake_t entitlement_id;
    dcc_snowflake_t subscription_id;
    dcc_snowflake_t promotion_id;
    dcc_snowflake_t emoji_id;
    dcc_snowflake_t rule_id;
    dcc_snowflake_t alert_system_message_id;
    dcc_snowflake_t message_author_id;
    dcc_snowflake_t sound_id;
    dcc_snowflake_t animation_id;
    dcc_snowflake_t entity_id;
    dcc_snowflake_t creator_id;
    dcc_snowflake_t owner_id;
    dcc_snowflake_t afk_channel_id;
    dcc_snowflake_t system_channel_id;
    dcc_snowflake_t rules_channel_id;
    dcc_snowflake_t public_updates_channel_id;
    dcc_snowflake_t widget_channel_id;
    dcc_snowflake_t safety_alerts_channel_id;
    uint64_t timestamp;
    uint64_t flags;
    uint32_t type;
    uint32_t count;
    uint32_t chunk_index;
    uint32_t chunk_count;
    uint32_t action_type;
    uint32_t trigger_type;
    uint32_t target_type;
    uint32_t channel_type;
    uint32_t answer_id;
    uint32_t animation_type;
    uint32_t opcode;
    uint32_t max_age;
    uint32_t max_uses;
    uint32_t uses;
    uint32_t privacy_level;
    uint32_t entity_type;
    uint32_t event_type;
    uint32_t gift_code_flags;
    uint32_t max_presences;
    uint32_t max_members;
    uint32_t premium_subscription_count;
    uint32_t afk_timeout;
    uint32_t max_video_channel_users;
    uint32_t default_message_notifications;
    uint32_t premium_tier;
    uint32_t verification_level;
    uint32_t explicit_content_filter;
    uint32_t mfa_level;
    uint32_t nsfw_level;
    uint64_t since;
    double retry_after;
    double volume;
    uint8_t available;
    uint8_t enabled;
    uint8_t discoverable_disabled;
    uint8_t pending;
    uint8_t temporary;
    uint8_t burst;
    uint8_t newly_created;
    uint8_t deaf;
    uint8_t mute;
    uint8_t widget_enabled;
    uint8_t premium_progress_bar_enabled;
    const dcc_snowflake_t *ids;
    size_t ids_count;
    uint8_t ids_truncated;
    const dcc_snowflake_t *channel_ids;
    size_t channel_ids_count;
    uint8_t channel_ids_truncated;
    const dcc_snowflake_t *removed_member_ids;
    size_t removed_member_ids_count;
    uint8_t removed_member_ids_truncated;
    const dcc_snowflake_t *member_ids;
    size_t member_ids_count;
    uint8_t member_ids_truncated;
    const dcc_thread_member_t *added_members;
    size_t added_members_count;
    uint8_t added_members_truncated;
    const dcc_member_t *members;
    size_t members_count;
    uint8_t members_truncated;
    const dcc_snowflake_t *role_ids;
    size_t role_ids_count;
    uint8_t role_ids_truncated;
    const dcc_snowflake_t *not_found_ids;
    size_t not_found_ids_count;
    uint8_t not_found_ids_truncated;
    const dcc_snowflake_t *sku_ids;
    size_t sku_ids_count;
    uint8_t sku_ids_truncated;
    const dcc_snowflake_t *entitlement_ids;
    size_t entitlement_ids_count;
    uint8_t entitlement_ids_truncated;
    const dcc_gateway_activity_t *activities;
    size_t activities_count;
    uint8_t activities_truncated;
    const char *name;
    const char *description;
    const char *topic;
    const char *type_text;
    const char *desktop_status;
    const char *mobile_status;
    const char *web_status;
    const char *code;
    const char *status;
    const char *token;
    const char *endpoint;
    const char *emoji_name;
    const char *reason;
    const char *content;
    const char *matched_keyword;
    const char *matched_content;
    const char *timestamp_text;
    const char *join_timestamp;
    const char *created_at;
    const char *expires_at;
    const char *start_time;
    const char *end_time;
    const char *current_period_start;
    const char *current_period_end;
    const char *canceled_at;
    const char *joined_at;
    const char *premium_since;
    const char *communication_disabled_until;
    const char *nick;
    const char *icon;
    const char *avatar;
    const char *banner;
    const char *vanity_url_code;
    const char *preferred_locale;
    const char *splash;
    const char *discovery_splash;
    const char *nonce;
} dcc_gateway_event_data_t;

#endif
