#!/usr/bin/env python3
"""Validate dcc_new_app generated project defaults."""

from pathlib import Path
import sys


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: generated_app_contract.py GENERATED_APP_DIR", file=sys.stderr)
        return 2

    root = Path(sys.argv[1])
    main_c = root / "src" / "main.c"
    config_h = root / "src" / "config.h"
    ping_h = root / "src" / "ping.h"
    ping_c = root / "src" / "ping.c"
    profile_h = root / "src" / "profile.h"
    profile_c = root / "src" / "profile.c"
    cmake = root / "CMakeLists.txt"
    env_example = root / ".env.example"
    readme = root / "README.md"
    commands = root / "commands.json"

    errors: list[str] = []
    for path in (main_c, config_h, ping_h, ping_c, profile_h, profile_c, cmake, env_example, readme, commands):
        if not path.is_file():
            errors.append(f"missing generated file: {path}")

    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    main_text = main_c.read_text(encoding="utf-8")
    config_text = config_h.read_text(encoding="utf-8")
    ping_text = ping_c.read_text(encoding="utf-8")
    ping_header_text = ping_h.read_text(encoding="utf-8")
    profile_text = profile_c.read_text(encoding="utf-8")
    profile_header_text = profile_h.read_text(encoding="utf-8")
    cmake_text = cmake.read_text(encoding="utf-8")
    env_text = env_example.read_text(encoding="utf-8")
    readme_text = readme.read_text(encoding="utf-8")
    commands_text = commands.read_text(encoding="utf-8")

    required_main = (
        "dcc_app_load_dotenv()",
        "DCC_CONFIG(",
        'DCC_CONFIG_BOOL_DEFAULT("BOT_DEBUG", 0U, &config.debug)',
        'DCC_CONFIG_CHANNEL("LOG_CHANNEL", &config.log_channel)',
        'DCC_CONFIG_BOOL("FEATURE_ENABLED", &config.feature_enabled)',
        "/* dcc_new_app:config-bindings */",
        "DCC_RUN_APP_ENV(",
        "DCC_DEV_BOT(",
        "bot_config_t config = {0};",
        '#include "config.h"',
        '#include "ping.h"',
        '#include "profile.h"',
        "/* dcc_new_app:feature-includes */",
        "DCC_APP_USE(",
        "DCC_USE_FEATURE(ping, &config)",
        "DCC_USE_FEATURE(profile, &config)",
        "/* dcc_new_app:feature-modules */",
        "DCC_FRIENDLY_ERROR_FN(on_bot_error)",
        "DCC_APP_ERROR_HANDLER(on_bot_error, &config)",
        "/* dcc_new_app:error-handlers */",
        "/* dcc_new_app:error-handler-option */",
    )
    for needle in required_main:
        if needle not in main_text:
            errors.append(f"generated src/main.c missing {needle!r}")

    for needle in (
        "typedef struct bot_config",
        "uint8_t debug;",
        "dcc_snowflake_t log_channel;",
        "uint8_t feature_enabled;",
        "/* dcc_new_app:config-fields */",
        "bot_config_from_user_data",
        "bot_config_from_ctx",
        "BOT_CONFIG(user_data_)",
        "BOT_CTX_CONFIG(ctx_)",
    ):
        if needle not in config_text:
            errors.append(f"generated src/config.h missing {needle!r}")

    for needle in (
        "DCC_DECLARE_FEATURE(ping)",
    ):
        if needle not in ping_header_text:
            errors.append(f"generated src/ping.h missing {needle!r}")

    for needle in (
        '#include "config.h"',
        "DCC_DEFINE_PUBLIC_FEATURE(",
        "DCC_COMMAND_IMPL(on_ping)",
        "DCC_COMMAND_ROUTE_NO_OPTIONS_DATA(\"ping\", \"Reply with pong\", on_ping, user_data)",
        "DCC_CTX_STORE_U64_OR(ctx, \"ping.count\", 0U) + 1U",
        "DCC_CTX_STORE_SET_U64(ctx, \"ping.count\", count)",
        "DCC_CTX_REPLY_TEXT_F(ctx, \"pong #%llu\", (unsigned long long)count)",
        "DCC_CTX_REPLY_TEXT(ctx, \"pong\")",
    ):
        if needle not in ping_text:
            errors.append(f"generated src/ping.c missing {needle!r}")
    if "pong #%%llu" in ping_text:
        errors.append("generated src/ping.c should not escape the runtime pong format")

    for needle in (
        "DCC_DECLARE_FEATURE(profile)",
    ):
        if needle not in profile_header_text:
            errors.append(f"generated src/profile.h missing {needle!r}")

    for needle in (
        '#include "config.h"',
        "DCC_DEFINE_PUBLIC_FEATURE(",
        "profile",
        "typedef struct profile_args",
        "#define PROFILE_PARAMS(PARAM, type)",
        'PARAM(type, STRING_AUTOCOMPLETE, name, "name", "Name to echo", 0U, "there")',
        "DCC_COMMAND_ARGS_IMPL(on_profile, profile_args_t, command)",
        "DCC_CTX_REPLY_TEXT_F(ctx, \"profile: hello %s\", name)",
        "DCC_FEATURE_COMMAND_ROUTES(",
        "DCC_COMMAND_ROUTE_DATA(",
        "PROFILE_PARAMS",
        "DCC_HANDLER(on_profile_button)",
        "DCC_BUTTON_PREFIX_DATA(\"profile.\", on_profile_button, user_data)",
        "typedef struct on_profile_greet_args",
        "#define ON_PROFILE_GREET_PARAMS(PARAM, type)",
        "DCC_COMMAND_ARGS_IMPL(on_profile_greet, on_profile_greet_args_t, command)",
        "DCC_CTX_REPLY_TEXT_F(ctx, \"greet: hello %s\", name)",
        "DCC_ON_TYPED_SLASH_BUILDER_DATA_GUARDED(",
        "DCC_POLICY(",
        "DCC_OWNER_ONLY(123456789012345678ULL)",
        "DCC_CAN(DCC_PERMISSION_MANAGE_GUILD)",
        "DCC_RATE_LIMIT_USER(1U, 5000U)",
        "DCC_SLASH_PARAMS_BINDINGS(on_profile_greet_args_t, ON_PROFILE_GREET_PARAMS)",
        "Generated greet command",
        "typedef struct on_profile_greet_stats_args",
        "#define ON_PROFILE_GREET_STATS_PARAMS(PARAM, type)",
        "DCC_SUBCOMMAND_ARGS_IMPL(on_profile_greet_stats_subcommand, on_profile_greet_stats_args_t, command)",
        "DCC_CTX_REPLY_TEXT_F(ctx, \"greet/stats: hello %s\", name)",
        "DCC_FEATURE_SUBCOMMAND_ROUTES(",
        "DCC_SUBCOMMAND_ROUTE_DATA_GUARDED(",
        "DCC_HAS_ROLE(223456789012345678ULL)",
        "ON_PROFILE_GREET_STATS_PARAMS",
        "DCC_CMD_SUB_PARAMS(",
        "\"stats\"",
        "Generated stats subcommand",
        "DCC_BUTTON_ARGS_IMPL(on_profile_refresh_button, on_profile_refresh_button_args_t, button)",
        "typedef struct on_profile_refresh_button_args",
        "DCC_CTX_DONEF(",
        "\"profile.refresh clicked: %s\"",
        "DCC_FEATURE_BUTTON_ROUTES(",
        "#define ON_PROFILE_REFRESH_BUTTON_PARAMS(PARAM, type)",
        "PARAM(type, REQUIRED_CUSTOM_ID_SUFFIX, action, \"profile.\")",
        "DCC_BUTTON_PARAMS_DATA_POLICY(",
        "ON_PROFILE_REFRESH_BUTTON_PARAMS",
        "DCC_HAS_ANY_ROLE(323456789012345678ULL,423456789012345678ULL)",
        "DCC_SELECT_ARGS_IMPL(on_profile_role_select, on_profile_role_select_args_t, select)",
        "typedef struct on_profile_role_select_args",
        "\"profile.role selected: %s\"",
        "DCC_FEATURE_SELECT_ROUTES(",
        "#define ON_PROFILE_ROLE_SELECT_PARAMS(PARAM, type)",
        "PARAM(type, REQUIRED_FIRST_VALUE, value)",
        "DCC_SELECT_PARAMS_DATA_POLICY(",
        "ON_PROFILE_ROLE_SELECT_PARAMS",
        "DCC_ONLY_DM()",
        "DCC_MODAL_ARGS_IMPL(on_profile_edit_modal, on_profile_edit_modal_args_t, modal)",
        "typedef struct on_profile_edit_modal_args",
        "\"profile.edit submitted: %s\"",
        "DCC_FEATURE_MODAL_ROUTES(",
        "#define ON_PROFILE_EDIT_MODAL_PARAMS(PARAM, type)",
        "PARAM(type, REQUIRED_STRING, value, \"value\")",
        "DCC_MODAL_PARAMS_DATA_POLICY(",
        "ON_PROFILE_EDIT_MODAL_PARAMS",
        "DCC_ONLY_NSFW()",
        "DCC_AUTOCOMPLETE_ARGS_IMPL(on_profile_profile_autocomplete, profile_args_t, command)",
        "DCC_FEATURE_AUTOCOMPLETE_ROUTES(",
        "DCC_AUTOCOMPLETE_PARAMS_DATA_GUARDED(",
        "profile_args_t",
        "DCC_RATE_LIMIT_USER(2U, 3000U)",
        "DCC_CTX_AUTOCOMPLETE_MATCHING(",
        "DCC_AUTOCOMPLETE_STRING_CHOICE(\"Example\", \"example\")",
        "DCC_HANDLER(on_profile_inspect_user_user_menu)",
        "DCC_CTX_TARGET_DISPLAY_NAME_OR(ctx, \"unknown\")",
        "DCC_CTX_TARGET_USER_MENTION(ctx)",
        "DCC_FEATURE_CONTEXT_MENUS(",
        "DCC_USER_CONTEXT_MENU_DATA_GUARDED(",
        "\"inspect_user\"",
        "DCC_HANDLER(on_profile_quote_message_message_menu)",
        "const dcc_message_t *message = DCC_CTX_TARGET_MESSAGE(ctx)",
        "\"Selected message %llu:\\n%s\"",
        "DCC_MESSAGE_CONTEXT_MENU_DATA(\"quote_message\", on_profile_quote_message_message_menu, user_data)",
        "DCC_MIDDLEWARE_FN(on_profile_require_config_middleware)",
        "bot_config_t *config = BOT_CONFIG(user_data)",
        "return config != NULL ? DCC_OK : DCC_ERR_STATE;",
        "DCC_FEATURE_MIDDLEWARE(",
        "DCC_MIDDLEWARE_DATA(on_profile_require_config_middleware, user_data)",
        "DCC_READY_FN(on_profile_ready)",
        "DCC_READY_DATA(on_profile_ready, user_data)",
        "DCC_MEMBER_JOIN_FN(on_profile_member_join)",
        "DCC_MEMBER_JOIN_DATA(on_profile_member_join, user_data)",
        "#define ON_PROFILE_DASHBOARD_VIEW_ACTIONS",
        "DCC_VIEW_ACTION_PRIMARY(\"Refresh\", \"profile.dashboard.refresh\", on_profile_dashboard_view_refresh)",
        "DCC_VIEW_ACTION_SECONDARY(\"Edit\", \"profile.dashboard.edit\", on_profile_dashboard_view_edit)",
        "typedef struct on_profile_dashboard_view_args",
        "DCC_COMMAND_ARGS_IMPL(on_profile_dashboard_view, on_profile_dashboard_view_args_t, command)",
        "DCC_RESPOND_UI(",
        "DCC_VIEW_ACTION_ROW(ON_PROFILE_DASHBOARD_VIEW_ACTIONS)",
        "DCC_TYPED_SLASH_NO_OPTIONS_DATA(",
        "\"Open dashboard view\"",
        "DCC_HANDLER(on_profile_dashboard_view_refresh)",
        "DCC_HANDLER(on_profile_dashboard_view_edit)",
        "DCC_HANDLER(on_profile_dashboard_view_modal)",
        "DCC_FEATURE_VIEWS(",
        "DCC_VIEW_ACTION_ROUTES_DATA(",
        "ON_PROFILE_DASHBOARD_VIEW_ACTIONS",
        "DCC_VIEW_DATA(",
        "DCC_VIEW_MODAL(\"profile.dashboard.edit\", on_profile_dashboard_view_modal)",
        "/* dcc_new_app:view-routes */",
        "DCC_HANDLER(on_profile_status_latest_message)",
        "BOT_CONFIG(user_data)",
        "config->log_channel",
        "DCC_CTX_TRY(ctx, DCC_APP_PUBLISH_LATEST_STORE(",
        "\"profile.status.latest\"",
        "DCC_COMMAND_DATA(\"status\", \"Publish latest status message\", on_profile_status_latest_message, user_data)",
        "/* dcc_new_app:latest-message-routes */",
        "DCC_TASK_FN(on_profile_daily_status_latest_task)",
        "\"profile.daily_status.scheduled_latest\"",
        "DCC_TASK_LOOP_KST_DATA(\"09:00\", on_profile_daily_status_latest_task, user_data)",
        "DCC_MESSAGE_COMMAND_FN(on_profile_hello_message_command)",
        "DCC_MESSAGE_COMMAND_DATA(\"!\", \"hello\", on_profile_hello_message_command, user_data)",
        "DCC_APP_SEND_UI(app, message->channel_id, DCC_UI_TEXT(reply))",
        "DCC_TASK_FN(on_profile_heartbeat_task)",
        "DCC_TASK_LOOP_SECONDS_DATA(60U, on_profile_heartbeat_task, user_data)",
        "DCC_HANDLER(on_profile_gateway_status_action)",
        "DCC_GATEWAY_BOT_FETCH(DCC_CTX_APP(ctx))",
        "DCC_CTX_DONE(ctx, \"Gateway bot fetch queued.\")",
        "DCC_COMMAND_DATA_POLICY(\"gateway_status\", \"Generated gateway action\", on_profile_gateway_status_action, user_data",
        "typedef struct on_profile_dm_user_action_args",
        "#define ON_PROFILE_DM_USER_ACTION_PARAMS(PARAM, type)",
        "PARAM(type, USER, user, \"user\", \"User to DM\", 1U)",
        "PARAM(type, STRING, message, \"message\", \"Message to send\", 0U, \"Hello from DCC.\")",
        "DCC_COMMAND_ARGS_IMPL(on_profile_dm_user_action, on_profile_dm_user_action_args_t, command)",
        "DCC_USER_DM_SEND_TEXT(DCC_CTX_APP(ctx), command->user->id, message)",
        "DCC_COMMAND_ROUTE_DATA_POLICY(",
        "\"dm_user\"",
        "\"Generated dm action\"",
        "ON_PROFILE_DM_USER_ACTION_PARAMS",
        "typedef struct on_profile_grant_role_action_args",
        "#define ON_PROFILE_GRANT_ROLE_ACTION_PARAMS(PARAM, type)",
        "PARAM(type, ROLE, role, \"role\", \"Role to add\", 1U)",
        "DCC_COMMAND_ARGS_IMPL(on_profile_grant_role_action, on_profile_grant_role_action_args_t, command)",
        "DCC_MEMBER_ADD_ROLE(DCC_CTX_APP(ctx), guild_id, command->user->id, command->role->id)",
        "\"grant_role\"",
        "\"Generated role-add action\"",
        "ON_PROFILE_GRANT_ROLE_ACTION_PARAMS",
        "typedef struct on_profile_revoke_role_action_args",
        "#define ON_PROFILE_REVOKE_ROLE_ACTION_PARAMS(PARAM, type)",
        "PARAM(type, ROLE, role, \"role\", \"Role to remove\", 1U)",
        "DCC_COMMAND_ARGS_IMPL(on_profile_revoke_role_action, on_profile_revoke_role_action_args_t, command)",
        "DCC_MEMBER_REMOVE_ROLE(DCC_CTX_APP(ctx), guild_id, command->user->id, command->role->id)",
        "\"revoke_role\"",
        "\"Generated role-remove action\"",
        "ON_PROFILE_REVOKE_ROLE_ACTION_PARAMS",
        "DCC_CAN(DCC_PERMISSION_MANAGE_ROLES)",
        "typedef struct on_profile_announcement_modal_args",
        "#define ON_PROFILE_ANNOUNCEMENT_MODAL_PARAMS(PARAM, type)",
        "on_profile_announcement_copy_store_text",
        "DCC_MODAL_V2_FIELD_TEXT_PLACEHOLDER(\"profile.announcement.title\", \"Title\", \"Announcement title\")",
        "DCC_MODAL_V2_FIELD_PARAGRAPH_PLACEHOLDER(\"profile.announcement.body\", \"Body\", \"What should everyone know?\")",
        "DCC_CTX_TRY(ctx, DCC_CTX_STORE_SET(ctx, title_key, title))",
        "DCC_CTX_TRY(ctx, DCC_CTX_STORE_GET(ctx, title_key, title, sizeof(title), NULL))",
        "DCC_CTX_REQUIRE_STORE(ctx, \"App store is not configured.\")",
        "DCC_UI_SUCCESS(\"Send\", \"profile.announcement.send\")",
        "DCC_CTX_TRY(ctx, DCC_CTX_SEND_UI(ctx, DCC_UI_CARD_ACCENT(0x5865F2, DCC_UI_TEXT(announcement))))",
        "DCC_COMMAND_DATA_POLICY(\"announcement\", \"Generated announcement preset\", on_profile_announcement, user_data",
        "DCC_BUTTON_PREFIX_DATA_POLICY(\"profile.announcement.\", on_profile_announcement_button, user_data",
        "DCC_MODAL_PARAMS_DATA_POLICY(\"profile.announcement.compose\", on_profile_announcement_modal_args_t, on_profile_announcement_modal, user_data, ON_PROFILE_ANNOUNCEMENT_MODAL_PARAMS",
        "on_profile_confirm",
        "DCC_CONFIRM_MESSAGE(\"Run this action?\", \"profile.confirm.yes\", \"profile.confirm.no\")",
        "on_profile_confirm_button",
        "DCC_COMMAND_DATA_POLICY(\"confirm\", \"Generated confirm preset\", on_profile_confirm, user_data",
        "DCC_BUTTON_PREFIX_DATA_POLICY(\"profile.confirm.\", on_profile_confirm_button, user_data",
        "on_profile_paginator",
        "DCC_PAGINATOR_MESSAGE(\"Page 1/3\", \"profile.paginator.prev\", \"profile.paginator.next\", 1U, 0U)",
        "on_profile_paginator_button",
        "DCC_COMMAND_DATA(\"paginator\", \"Generated paginator preset\", on_profile_paginator, user_data)",
        "DCC_BUTTON_PREFIX_DATA(\"profile.paginator.\", on_profile_paginator_button, user_data)",
        "typedef struct on_profile_form_modal_args",
        "#define ON_PROFILE_FORM_MODAL_PARAMS(PARAM, type)",
        "DCC_SHOW_MODAL_V2(",
        "DCC_MODAL_V2_FIELD_TEXT_PLACEHOLDER(\"profile.form.name\", \"Name\", \"Enter a value\")",
        "on_profile_form_modal",
        "DCC_CTX_DONEF(ctx, \"Submitted form for %s\", name)",
        "DCC_COMMAND_DATA_POLICY(\"form\", \"Generated form preset\", on_profile_form, user_data",
        "DCC_MODAL_PARAMS_DATA_POLICY(\"profile.form\", on_profile_form_modal_args_t, on_profile_form_modal, user_data, ON_PROFILE_FORM_MODAL_PARAMS",
        "DCC_OWNER_ONLY(523456789012345678ULL)",
        "typedef struct on_profile_settings_modal_args",
        "#define ON_PROFILE_SETTINGS_MODAL_PARAMS(PARAM, type)",
        "DCC_SETTINGS_PANEL_V2(",
        "DCC_MODAL_V2_FIELD_CHECKBOX(\"profile.settings.enabled\", \"Enabled\", 1U)",
        "on_profile_settings_button",
        "DCC_COMMAND_DATA_POLICY(\"settings\", \"Generated settings preset\", on_profile_settings, user_data",
        "DCC_BUTTON_PREFIX_DATA_POLICY(\"profile.settings.\", on_profile_settings_button, user_data",
        "DCC_MODAL_PARAMS_DATA_POLICY(\"profile.settings.edit\", on_profile_settings_modal_args_t, on_profile_settings_modal, user_data, ON_PROFILE_SETTINGS_MODAL_PARAMS",
        "DCC_HAS_ROLE(623456789012345678ULL)",
        "typedef struct on_profile_wizard_modal_args",
        "#define ON_PROFILE_WIZARD_MODAL_PARAMS(PARAM, type)",
        "DCC_V2_BUTTON_PRIMARY(\"Start\", \"profile.wizard.start\")",
        "DCC_SHOW_MODAL_V2(",
        "DCC_MODAL_V2_FIELD_TEXT_PLACEHOLDER(\"profile.wizard.name\", \"Name\", \"Enter a name\")",
        "DCC_MODAL_V2_FIELD_PARAGRAPH_OPTIONAL_PLACEHOLDER(\"profile.wizard.note\", \"Note\", \"Optional note\")",
        "on_profile_wizard_button",
        "on_profile_wizard_modal",
        "DCC_COMMAND_DATA_POLICY(\"wizard\", \"Generated wizard preset\", on_profile_wizard, user_data",
        "DCC_BUTTON_PREFIX_DATA_POLICY(\"profile.wizard.\", on_profile_wizard_button, user_data",
        "DCC_MODAL_PARAMS_DATA_POLICY(\"profile.wizard.step1\", on_profile_wizard_modal_args_t, on_profile_wizard_modal, user_data, ON_PROFILE_WIZARD_MODAL_PARAMS",
        "DCC_RATE_LIMIT_USER(1U, 1000U)",
        "on_profile_counter",
        "on_profile_counter_button",
        "DCC_CTX_STORE_U64_OR(ctx, \"profile.counter.count\", 0U)",
        "DCC_CTX_STORE_SET_U64(ctx, \"profile.counter.count\", count)",
        "DCC_UI_PRIMARY(\"+1\", \"profile.counter.inc\")",
        "DCC_UI_SECONDARY(\"Reset\", \"profile.counter.reset\")",
        "DCC_COMMAND_DATA_POLICY(\"counter\", \"Generated counter preset\", on_profile_counter, user_data",
        "DCC_BUTTON_PREFIX_DATA_POLICY(\"profile.counter.\", on_profile_counter_button, user_data",
        "DCC_RATE_LIMIT_USER(5U, 10000U)",
        "typedef struct on_profile_crud_modal_args",
        "#define ON_PROFILE_CRUD_MODAL_PARAMS(PARAM, type)",
        "on_profile_crud_render",
        "DCC_CTX_REQUIRE_STORE(ctx, \"App store is not configured.\")",
        "DCC_CTX_STORE_U64_OR(ctx, \"profile.crud.count\", 0U)",
        "DCC_CTX_STORE_SET(ctx, item_key, name)",
        "DCC_CTX_STORE_DELETE(ctx, item_key)",
        "DCC_UI_PRIMARY(\"Add\", \"profile.crud.add\")",
        "DCC_UI_SECONDARY(\"Delete last\", \"profile.crud.delete_last\")",
        "DCC_UI_DANGER(\"Clear\", \"profile.crud.clear\")",
        "DCC_MODAL_V2_FIELD_TEXT_PLACEHOLDER(\"profile.crud.name\", \"Name\", \"Item name\")",
        "DCC_COMMAND_DATA_POLICY(\"crud\", \"Generated CRUD preset\", on_profile_crud, user_data",
        "DCC_BUTTON_PREFIX_DATA_POLICY(\"profile.crud.\", on_profile_crud_button, user_data",
        "DCC_MODAL_PARAMS_DATA_POLICY(\"profile.crud.create\", on_profile_crud_modal_args_t, on_profile_crud_modal, user_data, ON_PROFILE_CRUD_MODAL_PARAMS",
        "on_profile_help_page_text",
        "on_profile_help_render",
        "DCC_UI_PRIMARY(\"Commands\", \"profile.help.commands\")",
        "DCC_UI_SECONDARY(\"Components\", \"profile.help.components\")",
        "DCC_UI_SECONDARY(\"About\", \"profile.help.about\")",
        "DCC_COMMAND_DATA(\"help\", \"Generated help preset\", on_profile_help, user_data)",
        "DCC_BUTTON_PREFIX_DATA(\"profile.help.\", on_profile_help_button, user_data)",
        "typedef struct on_profile_menu_select_args",
        "#define ON_PROFILE_MENU_SELECT_PARAMS(PARAM, type)",
        "DCC_UI_STRING_SELECT(",
        "DCC_SELECT_OPTION_DESC(\"Overview\", \"overview\", \"Show the overview panel\")",
        "DCC_SELECT_OPTION_DESC(\"Status\", \"status\", \"Show current status\")",
        "DCC_SELECT_OPTION_DESC(\"Help\", \"help\", \"Show help actions\")",
        "DCC_SELECT_ARGS_IMPL(on_profile_menu_select, on_profile_menu_select_args_t, select)",
        "DCC_COMMAND_DATA_POLICY(\"menu\", \"Generated menu preset\", on_profile_menu, user_data",
        "DCC_SELECT_PARAMS_DATA_POLICY(\"profile.menu\", on_profile_menu_select_args_t, on_profile_menu_select, user_data, ON_PROFILE_MENU_SELECT_PARAMS",
        "DCC_ONLY_DM()",
        "on_profile_poll_render",
        "DCC_CTX_STORE_U64_OR(ctx, \"profile.poll.yes\", 0U)",
        "DCC_CTX_STORE_U64_OR(ctx, \"profile.poll.no\", 0U)",
        "DCC_UI_SUCCESS(\"Yes\", \"profile.poll.yes\")",
        "DCC_UI_DANGER(\"No\", \"profile.poll.no\")",
        "DCC_UI_SECONDARY(\"Reset\", \"profile.poll.reset\")",
        "DCC_COMMAND_DATA_POLICY(\"poll\", \"Generated poll preset\", on_profile_poll, user_data",
        "DCC_BUTTON_PREFIX_DATA_POLICY(\"profile.poll.\", on_profile_poll_button, user_data",
        "DCC_RATE_LIMIT_USER(3U, 10000U)",
        "on_profile_profile_card_render",
        "const dcc_user_t *user = DCC_CTX_USER(ctx)",
        "const dcc_member_t *member = DCC_CTX_MEMBER(ctx)",
        "const dcc_guild_t *guild = DCC_CTX_GUILD(ctx)",
        "const dcc_channel_t *channel = DCC_CTX_CHANNEL(ctx)",
        "DCC_UI_SECONDARY(\"Refresh\", \"profile.profile_card.refresh\")",
        "DCC_COMMAND_DATA(\"profile_card\", \"Generated profile preset\", on_profile_profile_card, user_data)",
        "DCC_BUTTON_PREFIX_DATA(\"profile.profile_card.\", on_profile_profile_card_button, user_data)",
        "ON_PROFILE_ROLES_ALPHA_ROLE_ID",
        "ON_PROFILE_ROLES_BETA_ROLE_ID",
        "ON_PROFILE_ROLES_GAMMA_ROLE_ID",
        "typedef struct on_profile_roles_select_args",
        "#define ON_PROFILE_ROLES_SELECT_PARAMS(PARAM, type)",
        "DCC_UI_STRING_SELECT(",
        "DCC_SELECT_OPTION_DESC(\"Alpha\", \"alpha\", \"Replace the generated Alpha role id\")",
        "DCC_UI_SECONDARY(\"Remove Alpha\", \"profile.roles.remove_alpha\")",
        "DCC_CTX_TRY_MSG(",
        "DCC_CTX_ADD_AUTHOR_ROLE(ctx, role_id)",
        "DCC_CTX_REMOVE_AUTHOR_ROLE(ctx, role_id)",
        "DCC_COMMAND_DATA_POLICY(\"roles\", \"Generated role menu preset\", on_profile_roles, user_data",
        "DCC_SELECT_PARAMS_DATA_POLICY(\"profile.roles.pick\", on_profile_roles_select_args_t, on_profile_roles_select, user_data, ON_PROFILE_ROLES_SELECT_PARAMS",
        "DCC_BUTTON_PREFIX_DATA_POLICY(\"profile.roles.\", on_profile_roles_button, user_data",
        "DCC_ONLY_GUILD()",
        "typedef struct on_profile_ticket_modal_args",
        "#define ON_PROFILE_TICKET_MODAL_PARAMS(PARAM, type)",
        "DCC_UI_PRIMARY(\"Open ticket\", \"profile.ticket.open\")",
        "DCC_MODAL_V2_FIELD_TEXT_PLACEHOLDER(\"profile.ticket.subject\", \"Subject\", \"What do you need help with?\")",
        "DCC_MODAL_V2_FIELD_PARAGRAPH_OPTIONAL_PLACEHOLDER(\"profile.ticket.details\", \"Details\", \"Add context for the team\")",
        "DCC_CTX_STORE_U64_OR(ctx, \"profile.ticket.ticket_count\", 0U) + 1U",
        "DCC_CTX_TRY(ctx, DCC_CTX_STORE_SET_U64(ctx, \"profile.ticket.ticket_count\", ticket_id))",
        "DCC_UI_DANGER(\"Close\", \"profile.ticket.close\")",
        "DCC_HANDLER(on_profile_ticket_button)",
        "DCC_MODAL_ARGS_IMPL(on_profile_ticket_modal, on_profile_ticket_modal_args_t, form)",
        "DCC_COMMAND_DATA_POLICY(\"ticket\", \"Generated ticket preset\", on_profile_ticket, user_data",
        "DCC_BUTTON_PREFIX_DATA_POLICY(\"profile.ticket.\", on_profile_ticket_button, user_data",
        "DCC_MODAL_PARAMS_DATA_POLICY(\"profile.ticket.create\", on_profile_ticket_modal_args_t, on_profile_ticket_modal, user_data, ON_PROFILE_TICKET_MODAL_PARAMS",
        "ON_PROFILE_WELCOME_CHANNEL_ID",
        "on_profile_welcome_build_text",
        "DCC_MEMBER_JOIN_FN(on_profile_welcome_member)",
        "DCC_APP_SEND_UI(app, ON_PROFILE_WELCOME_CHANNEL_ID",
        "DCC_COMMAND_DATA(\"welcome\", \"Generated welcome preset\", on_profile_welcome, user_data)",
        "DCC_MEMBER_JOIN_DATA(on_profile_welcome_member, user_data)",
        "typedef struct on_profile_flow_modal_args",
        "#define ON_PROFILE_FLOW_MODAL_PARAMS(PARAM, type)",
        "DCC_MODAL_V2_FIELD_TEXT_PLACEHOLDER(\"profile.flow.title\", \"Title\", \"Enter a title\")",
        "DCC_MODAL_V2_FIELD_PARAGRAPH_OPTIONAL_PLACEHOLDER(\"profile.flow.note\", \"Note\", \"Optional note\")",
        "DCC_UI_SUCCESS(\"Confirm\", \"profile.flow.confirm\")",
        "DCC_UI_SECONDARY(\"Edit\", \"profile.flow.edit\")",
        "DCC_UI_DANGER(\"Cancel\", \"profile.flow.cancel\")",
        "DCC_HANDLER(on_profile_flow_button)",
        "DCC_MODAL_ARGS_IMPL(on_profile_flow_modal, on_profile_flow_modal_args_t, form)",
        "DCC_COMMAND_DATA_POLICY(\"flow\", \"Generated flow preset\", on_profile_flow, user_data",
        "DCC_BUTTON_PREFIX_DATA_POLICY(\"profile.flow.\", on_profile_flow_button, user_data",
        "DCC_MODAL_PARAMS_DATA_POLICY(\"profile.flow.input\", on_profile_flow_modal_args_t, on_profile_flow_modal, user_data, ON_PROFILE_FLOW_MODAL_PARAMS",
        "/* dcc_new_app:preset-slash-routes */",
        "/* dcc_new_app:command-handlers */",
        "/* dcc_new_app:middleware-routes */",
        "/* dcc_new_app:middleware-extension */",
        "/* dcc_new_app:slash-routes */",
        "/* dcc_new_app:typed-subcommand-routes */",
        "/* dcc_new_app:subcommand-options */",
        "/* dcc_new_app:component-routes */",
        "/* dcc_new_app:view-extension */",
        "/* dcc_new_app:typed-button-routes */",
        "/* dcc_new_app:typed-button-extension */",
        "/* dcc_new_app:typed-select-routes */",
        "/* dcc_new_app:typed-select-extension */",
        "/* dcc_new_app:typed-modal-routes */",
        "/* dcc_new_app:typed-modal-extension */",
        "/* dcc_new_app:typed-autocomplete-routes */",
        "/* dcc_new_app:context-menu-routes */",
        "/* dcc_new_app:context-menu-extension */",
        "/* dcc_new_app:event-routes */",
        "/* dcc_new_app:message-command-routes */",
        "/* dcc_new_app:task-routes */",
    ):
        if needle not in profile_text:
            errors.append(f"generated src/profile.c missing {needle!r}")

    if "DCC_REPLY_VALIDATION_ERROR(ctx, status)" in profile_text:
        errors.append("generated src/profile.c should use DCC_CTX_TRY for status-returning handler calls")

    for needle in (
        "src/ping.c",
        "src/profile.c",
        "# dcc_new_app:feature-sources",
    ):
        if needle not in cmake_text:
            errors.append(f"generated CMakeLists.txt missing {needle!r}")

    for needle in (
        '"name": "ping"',
        '"name": "profile"',
        '"description": "Generated profile command"',
        '"name": "greet"',
        '"description": "Generated greet command"',
        '"name": "stats"',
        '"description": "Generated stats subcommand"',
        '"name": "name"',
        '"autocomplete": true',
        '"name": "inspect_user"',
        '"type": 2',
        '"name": "quote_message"',
        '"type": 3',
        '"name": "dashboard"',
        '"description": "Open dashboard view"',
        '"name": "announcement"',
        '"description": "Generated announcement preset"',
        '"name": "confirm"',
        '"description": "Generated confirm preset"',
        '"name": "paginator"',
        '"description": "Generated paginator preset"',
        '"name": "form"',
        '"description": "Generated form preset"',
        '"name": "settings"',
        '"description": "Generated settings preset"',
        '"name": "wizard"',
        '"description": "Generated wizard preset"',
        '"name": "counter"',
        '"description": "Generated counter preset"',
        '"name": "crud"',
        '"description": "Generated CRUD preset"',
        '"name": "help"',
        '"description": "Generated help preset"',
        '"name": "menu"',
        '"description": "Generated menu preset"',
        '"name": "poll"',
        '"description": "Generated poll preset"',
        '"name": "profile_card"',
        '"description": "Generated profile preset"',
        '"name": "roles"',
        '"description": "Generated role menu preset"',
        '"name": "ticket"',
        '"description": "Generated ticket preset"',
        '"name": "welcome"',
        '"description": "Generated welcome preset"',
        '"name": "flow"',
        '"description": "Generated flow preset"',
        '"name": "status"',
        '"description": "Publish latest status message"',
        '"name": "gateway_status"',
        '"description": "Generated gateway action"',
        '"name": "dm_user"',
        '"description": "Generated dm action"',
        '"description": "User to DM"',
        '"description": "Message to send"',
        '"type": 6',
        '"name": "grant_role"',
        '"description": "Generated role-add action"',
        '"description": "Role to add"',
        '"type": 8',
        '"name": "revoke_role"',
        '"description": "Generated role-remove action"',
        '"description": "Role to remove"',
    ):
        if needle not in commands_text:
            errors.append(f"commands.json missing {needle!r}")

    if "DCC_APPLICATION_ID=" in env_text:
        errors.append(".env.example should not require DCC_APPLICATION_ID for app auto-sync")
    if "DCC_COMMAND_SYNC=" in env_text:
        errors.append(".env.example should not enable explicit env command sync")
    for needle in (
        "DCC_TOKEN=replace-me",
        "DCC_INTENTS=default",
        "DCC_AUTO_DEFER_MS=1500",
        "DCC_AUTO_DEFER_EPHEMERAL=true",
        "BOT_DEBUG=false",
        "LOG_CHANNEL=123456789012345678",
        "FEATURE_ENABLED=false",
        "DCC_STORE_FILE=bot-state.kv",
        "# DCC_COMMAND_GUILD_ID=123456789012345678",
        "# dcc_new_app:config-env",
    ):
        if needle not in env_text:
            errors.append(f".env.example missing {needle!r}")

    for needle in (
        "DCC_DEV_BOT(",
        "DCC_DEV_BOT(",
        "DCC_CONFIG(",
        "BOT_DEBUG",
        "DCC_RUN_APP_ENV(",
        "DCC_BUTTON(\"custom.id\", on_click)",
        "DCC_MODAL(\"custom.id\", on_submit)",
        "DCC_FRIENDLY_ERROR_FN(...)",
        "DCC_APP_ERROR_HANDLER",
        "DCC_COMMAND_IMPL",
        "DCC_BUTTON_PARAMS*",
        "DCC_SELECT_PARAMS*",
        "DCC_MODAL_PARAMS*",
        "DCC_DEFINE_PUBLIC_FEATURE",
        "DCC_USE_FEATURE",
        "DCC_APP_USE",
        "DCC_FEATURE_COMMAND_ROUTES",
        "DCC_COMMAND_ROUTE_NO_OPTIONS",
        "DCC_COMMAND_ROUTE",
        "DCC_CTX_REPLY_TEXT_F(ctx, \"pong #%llu\", (unsigned long long)count)",
        "DCC_UI_*",
        "*_PARAMS",
        "DCC_CTX_STORE_U64_OR(...)",
        "dcc_new_app add feature . profile",
        "dcc_new_app add command . profile greet",
        "dcc_new_app add subcommand . profile greet stats",
        "dcc_new_app add button . profile refresh",
        "dcc_new_app add select . profile role",
        "dcc_new_app add modal . profile edit",
        "dcc_new_app add autocomplete . profile profile",
        "dcc_new_app add context-menu . profile inspect_user user --guild-only",
        "dcc_new_app add context-menu . profile quote_message message",
        "dcc_new_app add middleware . profile require_config config",
        "dcc_new_app add event . profile ready",
        "dcc_new_app add view . profile dashboard",
        "dcc_new_app add config . log_channel channel LOG_CHANNEL",
        "dcc_new_app add error-handler . bot_error friendly",
        "dcc_new_app add latest-message . profile status log_channel",
        "dcc_new_app add scheduled-latest . profile daily_status log_channel --daily-kst 09:00",
        "dcc_new_app add message-command . profile hello --prefix '!'",
        "dcc_new_app add task . profile heartbeat --every-seconds 60",
        "dcc_new_app add action . profile gateway_status gateway --guild-only",
        "dcc_new_app add action . profile dm_user dm --guild-only",
        "dcc_new_app add action . profile grant_role role-add --guild-only --permission DCC_PERMISSION_MANAGE_ROLES",
        "dcc_new_app add preset . profile announcement --guild-only",
        "dcc_new_app add preset . profile confirm",
        "dcc_new_app add preset . profile paginator",
        "dcc_new_app add preset . profile form",
        "dcc_new_app add preset . profile settings",
        "dcc_new_app add preset . profile wizard",
        "dcc_new_app add preset . profile counter",
        "dcc_new_app add preset . profile crud",
        "dcc_new_app add preset . profile help",
        "dcc_new_app add preset . profile menu",
        "dcc_new_app add preset . profile poll",
        "dcc_new_app add preset . profile profile --name profile_card",
        "dcc_new_app add preset . profile roles --guild-only",
        "dcc_new_app add preset . profile ticket",
        "dcc_new_app add preset . profile welcome",
        "dcc_new_app add preset . profile flow",
        "DCC_STORE_FILE",
        "DCC_CTX_STORE_U64_OR(...)",
        "DCC_CTX_STORE_SET_U64(...)",
        "infers the application id",
        "DCC_APPLICATION_ID=your-application-id",
    ):
        if needle not in readme_text:
            errors.append(f"README.md missing {needle!r}")

    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    print("generated app contract passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
