#ifndef DCC_SUGAR_APP_PARAMS_ALIASES_CORE_H
#define DCC_SUGAR_APP_PARAMS_ALIASES_CORE_H

#include <dcc/sugar/app_params/modal_bindings.h>
#include <dcc/sugar/app_params/component_bindings.h>

#define DCC_MODAL_PARAMS_DATA_VALIDATED(...) DCC_ON_MODAL_PARAMS_DATA_VALIDATED(__VA_ARGS__)
#define DCC_MODAL_PARAMS_VALIDATED(...) DCC_ON_MODAL_PARAMS_VALIDATED(__VA_ARGS__)
#define DCC_MODAL_PARAMS_DATA(...) DCC_ON_MODAL_PARAMS_DATA(__VA_ARGS__)
#define DCC_MODAL_PARAMS(...) DCC_ON_MODAL_PARAMS(__VA_ARGS__)
#define DCC_MODAL_PARAMS_DATA_POLICY(...) DCC_ON_MODAL_PARAMS_DATA_POLICY(__VA_ARGS__)
#define DCC_MODAL_PARAMS_DATA_GUARDED(...) DCC_ON_MODAL_PARAMS_DATA_GUARDED(__VA_ARGS__)

#define DCC_MODAL_PREFIX_PARAMS_DATA_VALIDATED(...) DCC_ON_MODAL_PREFIX_PARAMS_DATA_VALIDATED(__VA_ARGS__)
#define DCC_MODAL_PREFIX_PARAMS_VALIDATED(...) DCC_ON_MODAL_PREFIX_PARAMS_VALIDATED(__VA_ARGS__)
#define DCC_MODAL_PREFIX_PARAMS_DATA(...) DCC_ON_MODAL_PREFIX_PARAMS_DATA(__VA_ARGS__)
#define DCC_MODAL_PREFIX_PARAMS(...) DCC_ON_MODAL_PREFIX_PARAMS(__VA_ARGS__)
#define DCC_MODAL_PREFIX_PARAMS_DATA_POLICY(...) DCC_ON_MODAL_PREFIX_PARAMS_DATA_POLICY(__VA_ARGS__)
#define DCC_MODAL_PREFIX_PARAMS_DATA_GUARDED(...) DCC_ON_MODAL_PREFIX_PARAMS_DATA_GUARDED(__VA_ARGS__)

#define DCC_BUTTON_PARAMS_DATA_VALIDATED(...) DCC_ON_BUTTON_PARAMS_DATA_VALIDATED(__VA_ARGS__)
#define DCC_BUTTON_PARAMS_VALIDATED(...) DCC_ON_BUTTON_PARAMS_VALIDATED(__VA_ARGS__)
#define DCC_BUTTON_PARAMS_DATA(...) DCC_ON_BUTTON_PARAMS_DATA(__VA_ARGS__)
#define DCC_BUTTON_PARAMS(...) DCC_ON_BUTTON_PARAMS(__VA_ARGS__)
#define DCC_BUTTON_PARAMS_DATA_POLICY(...) DCC_ON_BUTTON_PARAMS_DATA_POLICY(__VA_ARGS__)
#define DCC_BUTTON_PARAMS_DATA_GUARDED(...) DCC_ON_BUTTON_PARAMS_DATA_GUARDED(__VA_ARGS__)

#define DCC_BUTTON_PREFIX_PARAMS_DATA_VALIDATED(...) DCC_ON_BUTTON_PREFIX_PARAMS_DATA_VALIDATED(__VA_ARGS__)
#define DCC_BUTTON_PREFIX_PARAMS_VALIDATED(...) DCC_ON_BUTTON_PREFIX_PARAMS_VALIDATED(__VA_ARGS__)
#define DCC_BUTTON_PREFIX_PARAMS_DATA(...) DCC_ON_BUTTON_PREFIX_PARAMS_DATA(__VA_ARGS__)
#define DCC_BUTTON_PREFIX_PARAMS(...) DCC_ON_BUTTON_PREFIX_PARAMS(__VA_ARGS__)
#define DCC_BUTTON_PREFIX_PARAMS_DATA_POLICY(...) DCC_ON_BUTTON_PREFIX_PARAMS_DATA_POLICY(__VA_ARGS__)
#define DCC_BUTTON_PREFIX_PARAMS_DATA_GUARDED(...) DCC_ON_BUTTON_PREFIX_PARAMS_DATA_GUARDED(__VA_ARGS__)

#define DCC_SELECT_PARAMS_DATA_VALIDATED(...) DCC_ON_SELECT_PARAMS_DATA_VALIDATED(__VA_ARGS__)
#define DCC_SELECT_PARAMS_VALIDATED(...) DCC_ON_SELECT_PARAMS_VALIDATED(__VA_ARGS__)
#define DCC_SELECT_PARAMS_DATA(...) DCC_ON_SELECT_PARAMS_DATA(__VA_ARGS__)
#define DCC_SELECT_PARAMS(...) DCC_ON_SELECT_PARAMS(__VA_ARGS__)
#define DCC_SELECT_PARAMS_DATA_POLICY(...) DCC_ON_SELECT_PARAMS_DATA_POLICY(__VA_ARGS__)
#define DCC_SELECT_PARAMS_DATA_GUARDED(...) DCC_ON_SELECT_PARAMS_DATA_GUARDED(__VA_ARGS__)

#define DCC_SELECT_PREFIX_PARAMS_DATA_VALIDATED(...) DCC_ON_SELECT_PREFIX_PARAMS_DATA_VALIDATED(__VA_ARGS__)
#define DCC_SELECT_PREFIX_PARAMS_VALIDATED(...) DCC_ON_SELECT_PREFIX_PARAMS_VALIDATED(__VA_ARGS__)
#define DCC_SELECT_PREFIX_PARAMS_DATA(...) DCC_ON_SELECT_PREFIX_PARAMS_DATA(__VA_ARGS__)
#define DCC_SELECT_PREFIX_PARAMS(...) DCC_ON_SELECT_PREFIX_PARAMS(__VA_ARGS__)
#define DCC_SELECT_PREFIX_PARAMS_DATA_POLICY(...) DCC_ON_SELECT_PREFIX_PARAMS_DATA_POLICY(__VA_ARGS__)
#define DCC_SELECT_PREFIX_PARAMS_DATA_GUARDED(...) DCC_ON_SELECT_PREFIX_PARAMS_DATA_GUARDED(__VA_ARGS__)

#endif /* DCC_SUGAR_APP_PARAMS_ALIASES_CORE_H */
