#ifndef DCC_SUGAR_APP_PARAMS_ALIASES_SELECT_NAMESPACE_H
#define DCC_SUGAR_APP_PARAMS_ALIASES_SELECT_NAMESPACE_H

#include <dcc/sugar/app_params/select_namespace.h>

#define DCC_SELECT_NS_PARAMS_DATA_VALIDATED(...) DCC_ON_SELECT_NS_PARAMS_DATA_VALIDATED(__VA_ARGS__)
#define DCC_SELECT_NS_PARAMS_VALIDATED(...) DCC_ON_SELECT_NS_PARAMS_VALIDATED(__VA_ARGS__)
#define DCC_SELECT_NS_PARAMS_DATA(...) DCC_ON_SELECT_NS_PARAMS_DATA(__VA_ARGS__)
#define DCC_SELECT_NS_PARAMS(...) DCC_ON_SELECT_NS_PARAMS(__VA_ARGS__)
#define DCC_SELECT_NS_PARAMS_DATA_POLICY(...) DCC_ON_SELECT_NS_PARAMS_DATA_POLICY(__VA_ARGS__)
#define DCC_SELECT_NS_PARAMS_DATA_GUARDED(...) DCC_ON_SELECT_NS_PARAMS_DATA_GUARDED(__VA_ARGS__)
#define DCC_SELECT_NS_PARAMS_FN_VALIDATED(...) DCC_ON_SELECT_NS_PARAMS_FN_VALIDATED(__VA_ARGS__)
#define DCC_SELECT_NS_PARAMS_FN_DATA_VALIDATED(...) DCC_ON_SELECT_NS_PARAMS_FN_DATA_VALIDATED(__VA_ARGS__)
#define DCC_SELECT_NS_PARAMS_FN(...) DCC_ON_SELECT_NS_PARAMS_FN(__VA_ARGS__)
#define DCC_SELECT_NS_PARAMS_FN_DATA(...) DCC_ON_SELECT_NS_PARAMS_FN_DATA(__VA_ARGS__)
#define DCC_SELECT_NS_PARAMS_FN_DATA_POLICY(...) DCC_ON_SELECT_NS_PARAMS_FN_DATA_POLICY(__VA_ARGS__)
#define DCC_SELECT_NS_PARAMS_FN_DATA_GUARDED(...) DCC_ON_SELECT_NS_PARAMS_FN_DATA_GUARDED(__VA_ARGS__)

#define DCC_SELECT_NS_PREFIX_PARAMS_DATA_VALIDATED(...) DCC_ON_SELECT_NS_PREFIX_PARAMS_DATA_VALIDATED(__VA_ARGS__)
#define DCC_SELECT_NS_PREFIX_PARAMS_VALIDATED(...) DCC_ON_SELECT_NS_PREFIX_PARAMS_VALIDATED(__VA_ARGS__)
#define DCC_SELECT_NS_PREFIX_PARAMS_DATA(...) DCC_ON_SELECT_NS_PREFIX_PARAMS_DATA(__VA_ARGS__)
#define DCC_SELECT_NS_PREFIX_PARAMS(...) DCC_ON_SELECT_NS_PREFIX_PARAMS(__VA_ARGS__)
#define DCC_SELECT_NS_PREFIX_PARAMS_DATA_POLICY(...) DCC_ON_SELECT_NS_PREFIX_PARAMS_DATA_POLICY(__VA_ARGS__)
#define DCC_SELECT_NS_PREFIX_PARAMS_DATA_GUARDED(...) DCC_ON_SELECT_NS_PREFIX_PARAMS_DATA_GUARDED(__VA_ARGS__)
#define DCC_SELECT_NS_PREFIX_PARAMS_FN_VALIDATED(...) DCC_ON_SELECT_NS_PREFIX_PARAMS_FN_VALIDATED(__VA_ARGS__)
#define DCC_SELECT_NS_PREFIX_PARAMS_FN_DATA_VALIDATED(...) \
    DCC_ON_SELECT_NS_PREFIX_PARAMS_FN_DATA_VALIDATED(__VA_ARGS__)
#define DCC_SELECT_NS_PREFIX_PARAMS_FN(...) DCC_ON_SELECT_NS_PREFIX_PARAMS_FN(__VA_ARGS__)
#define DCC_SELECT_NS_PREFIX_PARAMS_FN_DATA(...) DCC_ON_SELECT_NS_PREFIX_PARAMS_FN_DATA(__VA_ARGS__)
#define DCC_SELECT_NS_PREFIX_PARAMS_FN_DATA_POLICY(...) DCC_ON_SELECT_NS_PREFIX_PARAMS_FN_DATA_POLICY(__VA_ARGS__)
#define DCC_SELECT_NS_PREFIX_PARAMS_FN_DATA_GUARDED(...) DCC_ON_SELECT_NS_PREFIX_PARAMS_FN_DATA_GUARDED(__VA_ARGS__)

#endif /* DCC_SUGAR_APP_PARAMS_ALIASES_SELECT_NAMESPACE_H */
