#ifndef DCC_SUGAR_APP_PARAMS_ALIASES_AUTOCOMPLETE_H
#define DCC_SUGAR_APP_PARAMS_ALIASES_AUTOCOMPLETE_H

#include <dcc/sugar/app_params/command_routes.h>

#define DCC_AUTOCOMPLETE_PARAMS_DATA_VALIDATED(...) DCC_ON_AUTOCOMPLETE_PARAMS_DATA_VALIDATED(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_PARAMS_VALIDATED(...) DCC_ON_AUTOCOMPLETE_PARAMS_VALIDATED(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_PARAMS_DATA(...) DCC_ON_AUTOCOMPLETE_PARAMS_DATA(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_PARAMS(...) DCC_ON_AUTOCOMPLETE_PARAMS(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_PARAMS_DATA_POLICY(...) DCC_ON_AUTOCOMPLETE_PARAMS_DATA_POLICY(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_PARAMS_DATA_GUARDED(...) DCC_ON_AUTOCOMPLETE_PARAMS_DATA_GUARDED(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_PARAMS_FN_DATA_VALIDATED(...) DCC_ON_AUTOCOMPLETE_PARAMS_FN_DATA_VALIDATED(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_PARAMS_FN_VALIDATED(...) DCC_ON_AUTOCOMPLETE_PARAMS_FN_VALIDATED(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_PARAMS_FN_DATA(...) DCC_ON_AUTOCOMPLETE_PARAMS_FN_DATA(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_PARAMS_FN(...) DCC_ON_AUTOCOMPLETE_PARAMS_FN(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_PARAMS_FN_DATA_POLICY(...) DCC_ON_AUTOCOMPLETE_PARAMS_FN_DATA_POLICY(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_PARAMS_FN_DATA_GUARDED(...) DCC_ON_AUTOCOMPLETE_PARAMS_FN_DATA_GUARDED(__VA_ARGS__)

#define DCC_AUTOCOMPLETE_BUILDER_PARAMS_DATA_VALIDATED(...) \
    DCC_ON_AUTOCOMPLETE_BUILDER_PARAMS_DATA_VALIDATED(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_BUILDER_PARAMS_VALIDATED(...) DCC_ON_AUTOCOMPLETE_BUILDER_PARAMS_VALIDATED(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_BUILDER_PARAMS_DATA(...) DCC_ON_AUTOCOMPLETE_BUILDER_PARAMS_DATA(__VA_ARGS__)
#define DCC_AUTOCOMPLETE_BUILDER_PARAMS(...) DCC_ON_AUTOCOMPLETE_BUILDER_PARAMS(__VA_ARGS__)

#endif /* DCC_SUGAR_APP_PARAMS_ALIASES_AUTOCOMPLETE_H */
