#ifndef DCC_REST_TYPES_INTERACTIONS_H
#define DCC_REST_TYPES_INTERACTIONS_H

#include <dcc/rest/base.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum dcc_interaction_response_type {
    DCC_INTERACTION_RESPONSE_PONG = 1,
    DCC_INTERACTION_RESPONSE_CHANNEL_MESSAGE_WITH_SOURCE = 4,
    DCC_INTERACTION_RESPONSE_DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE = 5,
    DCC_INTERACTION_RESPONSE_DEFERRED_UPDATE_MESSAGE = 6,
    DCC_INTERACTION_RESPONSE_UPDATE_MESSAGE = 7,
    DCC_INTERACTION_RESPONSE_AUTOCOMPLETE = 8,
    DCC_INTERACTION_RESPONSE_MODAL = 9,
    DCC_INTERACTION_RESPONSE_PREMIUM_REQUIRED = 10
} dcc_interaction_response_type_t;

#ifdef __cplusplus
}
#endif

#endif
