#ifndef DCC_SUGAR_FORMAT_RESPONSE_MACROS_H
#define DCC_SUGAR_FORMAT_RESPONSE_MACROS_H

#include <dcc/sugar/format/responses.h>
#include <dcc/sugar/format/macros.h>

#define DCC_FORMAT_ALLOC(out_text_, ...) dcc_sugar_format_alloc((out_text_), __VA_ARGS__)
#define DCC_FORMAT_FREE(text_) dcc_sugar_format_free((text_))

#define DCC_REPLYF(ctx_, ...) dcc_sugar_ctx_replyf((ctx_), __VA_ARGS__)
#define DCC_REPLY_PRIVATEF(ctx_, ...) dcc_sugar_ctx_reply_privatef((ctx_), __VA_ARGS__)
#define DCC_REPLY_SILENTF(ctx_, ...) dcc_sugar_ctx_reply_silentf((ctx_), __VA_ARGS__)
#define DCC_REPLY_NO_EMBEDSF(ctx_, ...) dcc_sugar_ctx_reply_no_embedsf((ctx_), __VA_ARGS__)
#define DCC_PRIVATEF(ctx_, ...) DCC_REPLY_PRIVATEF((ctx_), __VA_ARGS__)
#define DCC_RESPONDF(ctx_, ...) DCC_REPLYF((ctx_), __VA_ARGS__)
#define DCC_RESPOND_PRIVATEF(ctx_, ...) DCC_REPLY_PRIVATEF((ctx_), __VA_ARGS__)
#define DCC_RESPOND_SILENTF(ctx_, ...) DCC_REPLY_SILENTF((ctx_), __VA_ARGS__)
#define DCC_RESPOND_NO_EMBEDSF(ctx_, ...) DCC_REPLY_NO_EMBEDSF((ctx_), __VA_ARGS__)

#define DCC_FOLLOWUPF(ctx_, ...) dcc_sugar_ctx_followupf((ctx_), __VA_ARGS__)
#define DCC_FOLLOWUP_PRIVATEF(ctx_, ...) dcc_sugar_ctx_followup_privatef((ctx_), __VA_ARGS__)
#define DCC_FOLLOWUP_SILENTF(ctx_, ...) dcc_sugar_ctx_followup_silentf((ctx_), __VA_ARGS__)
#define DCC_SENDF(ctx_, ...) dcc_sugar_ctx_sendf((ctx_), __VA_ARGS__)
#define DCC_UPDATEF(ctx_, ...) dcc_sugar_ctx_updatef((ctx_), __VA_ARGS__)
#define DCC_UPDATE_MESSAGEF(ctx_, ...) DCC_UPDATEF((ctx_), __VA_ARGS__)
#define DCC_EDITF(ctx_, ...) dcc_sugar_ctx_editf((ctx_), __VA_ARGS__)
#define DCC_EDIT_ORIGINALF(ctx_, ...) DCC_EDITF((ctx_), __VA_ARGS__)
#define DCC_DONEF(ctx_, ...) dcc_sugar_ctx_okf((ctx_), __VA_ARGS__)
#define DCC_ACKF(ctx_, ...) DCC_DONEF((ctx_), __VA_ARGS__)
#define DCC_SUCCESSF(ctx_, title_, ...) dcc_sugar_ctx_successf((ctx_), (title_), __VA_ARGS__)
#define DCC_FAILF(ctx_, ...) dcc_sugar_ctx_failf((ctx_), __VA_ARGS__)
#define DCC_ERRORF(ctx_, title_, ...) dcc_sugar_ctx_errorf((ctx_), (title_), __VA_ARGS__)
#define DCC_DENYF(ctx_, ...) DCC_ERRORF((ctx_), "Permission denied", __VA_ARGS__)
#define DCC_BAD_INPUTF(ctx_, ...) DCC_ERRORF((ctx_), "Invalid input", __VA_ARGS__)
#define DCC_NOT_FOUNDF(ctx_, ...) DCC_ERRORF((ctx_), "Not found", __VA_ARGS__)
#define DCC_BUSYF(ctx_, ...) DCC_ERRORF((ctx_), "Please wait", __VA_ARGS__)

#define DCC_CTX_REPLYF(ctx_, ...) DCC_REPLYF((ctx_), __VA_ARGS__)
#define DCC_CTX_REPLY_F(ctx_, ...) DCC_REPLYF((ctx_), __VA_ARGS__)
#define DCC_CTX_REPLY_TEXT_F(ctx_, ...) DCC_REPLYF((ctx_), __VA_ARGS__)
#define DCC_CTX_RESPONDF(ctx_, ...) DCC_RESPONDF((ctx_), __VA_ARGS__)
#define DCC_CTX_RESPOND_F(ctx_, ...) DCC_RESPONDF((ctx_), __VA_ARGS__)
#define DCC_CTX_RESPOND_TEXT_F(ctx_, ...) DCC_RESPONDF((ctx_), __VA_ARGS__)
#define DCC_CTX_PRIVATEF(ctx_, ...) DCC_PRIVATEF((ctx_), __VA_ARGS__)
#define DCC_CTX_PRIVATE_F(ctx_, ...) DCC_PRIVATEF((ctx_), __VA_ARGS__)
#define DCC_CTX_EPHEMERAL_F(ctx_, ...) DCC_PRIVATEF((ctx_), __VA_ARGS__)
#define DCC_CTX_RESPOND_PRIVATEF(ctx_, ...) DCC_RESPOND_PRIVATEF((ctx_), __VA_ARGS__)
#define DCC_CTX_RESPOND_PRIVATE_F(ctx_, ...) DCC_RESPOND_PRIVATEF((ctx_), __VA_ARGS__)
#define DCC_CTX_RESPOND_EPHEMERAL_F(ctx_, ...) DCC_RESPOND_PRIVATEF((ctx_), __VA_ARGS__)
#define DCC_CTX_SILENTF(ctx_, ...) DCC_REPLY_SILENTF((ctx_), __VA_ARGS__)
#define DCC_CTX_SILENT_F(ctx_, ...) DCC_REPLY_SILENTF((ctx_), __VA_ARGS__)
#define DCC_CTX_RESPOND_SILENTF(ctx_, ...) DCC_RESPOND_SILENTF((ctx_), __VA_ARGS__)
#define DCC_CTX_RESPOND_SILENT_F(ctx_, ...) DCC_RESPOND_SILENTF((ctx_), __VA_ARGS__)
#define DCC_CTX_NO_EMBEDSF(ctx_, ...) DCC_REPLY_NO_EMBEDSF((ctx_), __VA_ARGS__)
#define DCC_CTX_NO_EMBEDS_F(ctx_, ...) DCC_REPLY_NO_EMBEDSF((ctx_), __VA_ARGS__)
#define DCC_CTX_RESPOND_NO_EMBEDSF(ctx_, ...) DCC_RESPOND_NO_EMBEDSF((ctx_), __VA_ARGS__)
#define DCC_CTX_RESPOND_NO_EMBEDS_F(ctx_, ...) DCC_RESPOND_NO_EMBEDSF((ctx_), __VA_ARGS__)
#define DCC_CTX_FOLLOWUPF(ctx_, ...) DCC_FOLLOWUPF((ctx_), __VA_ARGS__)
#define DCC_CTX_FOLLOWUP_F(ctx_, ...) DCC_FOLLOWUPF((ctx_), __VA_ARGS__)
#define DCC_CTX_FOLLOWUP_TEXT_F(ctx_, ...) DCC_FOLLOWUPF((ctx_), __VA_ARGS__)
#define DCC_CTX_FOLLOWUP_PRIVATEF(ctx_, ...) DCC_FOLLOWUP_PRIVATEF((ctx_), __VA_ARGS__)
#define DCC_CTX_FOLLOWUP_PRIVATE_F(ctx_, ...) DCC_FOLLOWUP_PRIVATEF((ctx_), __VA_ARGS__)
#define DCC_CTX_FOLLOWUP_EPHEMERAL_F(ctx_, ...) DCC_FOLLOWUP_PRIVATEF((ctx_), __VA_ARGS__)
#define DCC_CTX_FOLLOWUP_SILENTF(ctx_, ...) DCC_FOLLOWUP_SILENTF((ctx_), __VA_ARGS__)
#define DCC_CTX_FOLLOWUP_SILENT_F(ctx_, ...) DCC_FOLLOWUP_SILENTF((ctx_), __VA_ARGS__)
#define DCC_CTX_SENDF(ctx_, ...) DCC_SENDF((ctx_), __VA_ARGS__)
#define DCC_CTX_SEND_F(ctx_, ...) DCC_SENDF((ctx_), __VA_ARGS__)
#define DCC_CTX_SEND_TEXT_F(ctx_, ...) DCC_SENDF((ctx_), __VA_ARGS__)
#define DCC_CTX_UPDATEF(ctx_, ...) DCC_UPDATEF((ctx_), __VA_ARGS__)
#define DCC_CTX_UPDATE_F(ctx_, ...) DCC_UPDATEF((ctx_), __VA_ARGS__)
#define DCC_CTX_UPDATE_TEXT_F(ctx_, ...) DCC_UPDATEF((ctx_), __VA_ARGS__)
#define DCC_CTX_UPDATE_MESSAGEF(ctx_, ...) DCC_UPDATE_MESSAGEF((ctx_), __VA_ARGS__)
#define DCC_CTX_UPDATE_MESSAGE_F(ctx_, ...) DCC_UPDATE_MESSAGEF((ctx_), __VA_ARGS__)
#define DCC_CTX_EDITF(ctx_, ...) DCC_EDITF((ctx_), __VA_ARGS__)
#define DCC_CTX_EDIT_F(ctx_, ...) DCC_EDITF((ctx_), __VA_ARGS__)
#define DCC_CTX_EDIT_TEXT_F(ctx_, ...) DCC_EDITF((ctx_), __VA_ARGS__)
#define DCC_CTX_EDIT_ORIGINALF(ctx_, ...) DCC_EDIT_ORIGINALF((ctx_), __VA_ARGS__)
#define DCC_CTX_EDIT_ORIGINAL_F(ctx_, ...) DCC_EDIT_ORIGINALF((ctx_), __VA_ARGS__)
#define DCC_CTX_DONEF(ctx_, ...) DCC_DONEF((ctx_), __VA_ARGS__)
#define DCC_CTX_DONE_F(ctx_, ...) DCC_DONEF((ctx_), __VA_ARGS__)
#define DCC_CTX_ACKF(ctx_, ...) DCC_ACKF((ctx_), __VA_ARGS__)
#define DCC_CTX_ACK_F(ctx_, ...) DCC_ACKF((ctx_), __VA_ARGS__)
#define DCC_CTX_SUCCESSF(ctx_, title_, ...) DCC_SUCCESSF((ctx_), (title_), __VA_ARGS__)
#define DCC_CTX_SUCCESS_F(ctx_, title_, ...) DCC_SUCCESSF((ctx_), (title_), __VA_ARGS__)
#define DCC_CTX_FAILF(ctx_, ...) DCC_FAILF((ctx_), __VA_ARGS__)
#define DCC_CTX_FAIL_F(ctx_, ...) DCC_FAILF((ctx_), __VA_ARGS__)
#define DCC_CTX_ERRORF(ctx_, title_, ...) DCC_ERRORF((ctx_), (title_), __VA_ARGS__)
#define DCC_CTX_ERROR_F(ctx_, title_, ...) DCC_ERRORF((ctx_), (title_), __VA_ARGS__)
#define DCC_CTX_DENYF(ctx_, ...) DCC_DENYF((ctx_), __VA_ARGS__)
#define DCC_CTX_DENY_F(ctx_, ...) DCC_DENYF((ctx_), __VA_ARGS__)
#define DCC_CTX_BAD_INPUTF(ctx_, ...) DCC_BAD_INPUTF((ctx_), __VA_ARGS__)
#define DCC_CTX_BAD_INPUT_F(ctx_, ...) DCC_BAD_INPUTF((ctx_), __VA_ARGS__)
#define DCC_CTX_NOT_FOUNDF(ctx_, ...) DCC_NOT_FOUNDF((ctx_), __VA_ARGS__)
#define DCC_CTX_NOT_FOUND_F(ctx_, ...) DCC_NOT_FOUNDF((ctx_), __VA_ARGS__)
#define DCC_CTX_BUSYF(ctx_, ...) DCC_BUSYF((ctx_), __VA_ARGS__)
#define DCC_CTX_BUSY_F(ctx_, ...) DCC_BUSYF((ctx_), __VA_ARGS__)

#define DCC_APP_SENDF(app_, channel_id_, ...) dcc_sugar_app_sendf((app_), (channel_id_), __VA_ARGS__)
#define DCC_APP_SEND_F(app_, channel_id_, ...) DCC_APP_SENDF((app_), (channel_id_), __VA_ARGS__)
#define DCC_APP_SEND_TEXT_F(app_, channel_id_, ...) DCC_APP_SENDF((app_), (channel_id_), __VA_ARGS__)
#define DCC_CHANNEL_SENDF(app_, channel_id_, ...) DCC_APP_SENDF((app_), (channel_id_), __VA_ARGS__)
#define DCC_CHANNEL_SEND_F(app_, channel_id_, ...) DCC_CHANNEL_SENDF((app_), (channel_id_), __VA_ARGS__)
#define DCC_CHANNEL_SEND_TEXT_F(app_, channel_id_, ...) \
    DCC_CHANNEL_SENDF((app_), (channel_id_), __VA_ARGS__)
#define DCC_APP_EDITF(app_, channel_id_, message_id_, ...) \
    dcc_sugar_app_editf((app_), (channel_id_), (message_id_), __VA_ARGS__)
#define DCC_APP_EDIT_F(app_, channel_id_, message_id_, ...) \
    DCC_APP_EDITF((app_), (channel_id_), (message_id_), __VA_ARGS__)
#define DCC_APP_EDIT_TEXT_F(app_, channel_id_, message_id_, ...) \
    DCC_APP_EDITF((app_), (channel_id_), (message_id_), __VA_ARGS__)
#define DCC_MESSAGE_EDITF(app_, channel_id_, message_id_, ...) \
    DCC_APP_EDITF((app_), (channel_id_), (message_id_), __VA_ARGS__)
#define DCC_MESSAGE_EDIT_F(app_, channel_id_, message_id_, ...) \
    DCC_MESSAGE_EDITF((app_), (channel_id_), (message_id_), __VA_ARGS__)
#define DCC_MESSAGE_EDIT_TEXT_F(app_, channel_id_, message_id_, ...) \
    DCC_MESSAGE_EDITF((app_), (channel_id_), (message_id_), __VA_ARGS__)


#endif /* DCC_SUGAR_FORMAT_RESPONSE_MACROS_H */
