#!/usr/bin/env python3
"""Generate deterministic Markdown reference pages from installed DCC headers."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys


MARKER = "<!-- Generated by tools/generate_api_reference.py; do not edit. -->"
DECLARATION = re.compile(
    r"(?:/\*\*[\s\S]*?\*/\s*)?(?:DCC_API[\s\S]*?;|static\s+inline[\s\S]*?\n\})",
    re.MULTILINE,
)
NAME = re.compile(r"\b((?:dcc|DCC)_[A-Za-z0-9_]+)\s*\(")
MACRO = re.compile(r"^\s*#\s*define\s+(DCC_[A-Za-z0-9_]+)(?:\([^\n]*\))?", re.MULTILINE)


def installed_headers(source: Path) -> list[Path]:
    result = []
    for header in sorted((source / "include/dcc").rglob("*.h")):
        relative = header.relative_to(source / "include").as_posix()
        if (relative == "dcc/sugar.h" or relative.startswith("dcc/sugar/") or
                relative == "dcc/app/legacy.h" or relative == "dcc/rest/core.h" or
                relative.startswith("dcc/rest/core/") or
                relative == "dcc/rest/response_helpers.h"):
            continue
        result.append(header)
    return result


def normalize_signature(text: str) -> str:
    text = re.sub(r"/\*\*[\s\S]*?\*/", "", text)
    return " ".join(text.split())


def summary(text: str, name: str) -> str:
    comment = re.search(r"/\*\*([\s\S]*?)\*/", text)
    if comment is None:
        return f"Public DCC API declaration for `{name}`."
    cleaned = re.sub(r"^\s*\*\s?", "", comment.group(1), flags=re.MULTILINE)
    cleaned = " ".join(cleaned.replace("`", "").split())
    return cleaned or f"Public DCC API declaration for `{name}`."


def expected_files(source: Path) -> dict[Path, str]:
    output: dict[Path, str] = {}
    index_rows: list[tuple[str, str, int]] = []
    root = source / "docs/reference/api"
    for header in installed_headers(source):
        relative = header.relative_to(source / "include/dcc")
        text = header.read_text(encoding="utf-8")
        entries: list[tuple[str, str, str]] = []
        for match in DECLARATION.finditer(text):
            name_match = NAME.search(match.group(0))
            if name_match is not None:
                name = name_match.group(1)
                entries.append((name, normalize_signature(match.group(0)),
                                summary(match.group(0), name)))
        for name in sorted(set(MACRO.findall(text))):
            if name.endswith("_H"):
                continue
            entries.append((name, f"#define {name} ...",
                            f"Public macro `{name}`; arguments follow the owner header contract."))
        if not entries:
            continue
        entries.sort(key=lambda item: item[0].encode("utf-8"))
        page = root / relative.with_suffix(".md")
        lines = [MARKER, "", f"# `<dcc/{relative.as_posix()}>`", "",
                 f"Source: [`include/dcc/{relative.as_posix()}`](https://github.com/Feralthedogg/DCC/blob/v2.0.0/include/dcc/{relative.as_posix()})", ""]
        for name, signature, description in entries:
            lines.extend((f"## `{name}`", "", description, "", "```c", signature, "```", ""))
        output[page] = "\n".join(lines).rstrip() + "\n"
        index_rows.append((relative.as_posix(), relative.with_suffix(".md").as_posix(), len(entries)))
    index = [MARKER, "", "# DCC 2 API Reference", "",
             "Generated from the installed DCC 2.0.0 public header tree.", ""]
    for header, link, count in index_rows:
        index.append(f"- [`<dcc/{header}>`]({link}) — {count} public callable/macro entries")
    index.append("")
    output[root / "index.md"] = "\n".join(index)
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=Path(__file__).resolve().parents[1])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = args.source.resolve()
    expected = expected_files(source)
    root = source / "docs/reference/api"
    if args.write:
        for path, content in expected.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
        print(f"generated {len(expected)} API reference pages")
        return 0
    actual = set(root.rglob("*.md")) if root.is_dir() else set()
    if actual != set(expected):
        print("API reference page inventory is stale", file=sys.stderr)
        return 1
    stale = [path for path, content in expected.items()
             if path.read_text(encoding="utf-8") != content]
    if stale:
        print("stale API reference pages: " + ", ".join(str(path) for path in stale), file=sys.stderr)
        return 1
    print(f"API reference is current: {len(expected)} pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
