#ifndef DCC_VOICE_LIMITS_INTERNAL_H
#define DCC_VOICE_LIMITS_INTERNAL_H

#define DCC_VOICE_SSRC_MAP_CAP 128U
#define DCC_VOICE_PCM_BUFFER_CAP 65536U
#define DCC_VOICE_MIX_SOURCE_CAP 32U
#define DCC_VOICE_MIX_SAMPLE_CAP 5760U
#define DCC_VOICE_REORDER_QUEUE_CAP 16U
#define DCC_VOICE_REORDER_PACKET_CAP 4096U
#define DCC_VOICE_SEND_QUEUE_CAP 256U
#define DCC_VOICE_CLIENT_REGISTRY_CAP 32U
#define DCC_VOICE_SESSION_ID_CAP 256U
#define DCC_VOICE_SESSION_TOKEN_CAP 1024U
#define DCC_VOICE_ENDPOINT_CAP 512U
#define DCC_VOICE_CLOSE_REASON_CAP 256U
#define DCC_VOICE_UDP_HOST_CAP 256U
#define DCC_VOICE_DISCOVERY_ADDRESS_CAP 64U

#endif
