#ifndef DCC_INTENTS_H
#define DCC_INTENTS_H

#include <stdint.h>

enum {
    DCC_INTENT_GUILDS = 1ULL << 0,
    DCC_INTENT_GUILD_MEMBERS = 1ULL << 1,
    DCC_INTENT_GUILD_MODERATION = 1ULL << 2,
    DCC_INTENT_GUILD_EXPRESSIONS = 1ULL << 3,
    DCC_INTENT_GUILD_INTEGRATIONS = 1ULL << 4,
    DCC_INTENT_GUILD_WEBHOOKS = 1ULL << 5,
    DCC_INTENT_GUILD_INVITES = 1ULL << 6,
    DCC_INTENT_GUILD_VOICE_STATES = 1ULL << 7,
    DCC_INTENT_GUILD_PRESENCES = 1ULL << 8,
    DCC_INTENT_GUILD_MESSAGES = 1ULL << 9,
    DCC_INTENT_GUILD_MESSAGE_REACTIONS = 1ULL << 10,
    DCC_INTENT_GUILD_MESSAGE_TYPING = 1ULL << 11,
    DCC_INTENT_DIRECT_MESSAGES = 1ULL << 12,
    DCC_INTENT_DIRECT_MESSAGE_REACTIONS = 1ULL << 13,
    DCC_INTENT_DIRECT_MESSAGE_TYPING = 1ULL << 14,
    DCC_INTENT_MESSAGE_CONTENT = 1ULL << 15,
    DCC_INTENT_GUILD_SCHEDULED_EVENTS = 1ULL << 16,
    DCC_INTENT_AUTO_MODERATION_CONFIGURATION = 1ULL << 20,
    DCC_INTENT_AUTO_MODERATION_EXECUTION = 1ULL << 21,
    DCC_INTENT_GUILD_MESSAGE_POLLS = 1ULL << 24,
    DCC_INTENT_DIRECT_MESSAGE_POLLS = 1ULL << 25
};

typedef uint64_t dcc_intents_t;

#endif

