#ifndef DCC_JSON_KEY_ID_COLLECTION_CORE_ENTRIES_H
#define DCC_JSON_KEY_ID_COLLECTION_CORE_ENTRIES_H

#define DCC_JSON_KEY_ID_COLLECTION_CORE_ENTRIES(X) \
    X(IDS) \
    X(CHANNEL_IDS) \
    X(CHANNELS) \
    X(REMOVED_MEMBER_IDS) \
    X(ROLES) \
    X(ROLE_IDS) \
    X(NOT_FOUND) \
    X(RULE_ID) \
    X(ALERT_SYSTEM_MESSAGE_ID) \
    X(MESSAGE_AUTHOR_ID) \
    X(SOUND_ID) \
    X(ANIMATION_ID) \
    X(ENTITY_ID) \
    X(CREATOR_ID) \
    X(OWNER_ID) \
    X(EMOJI_ID)

#endif
