#ifndef DCC_JSON_KEY_ID_COLLECTION_RESOURCE_ENTRIES_H
#define DCC_JSON_KEY_ID_COLLECTION_RESOURCE_ENTRIES_H

#define DCC_JSON_KEY_ID_COLLECTION_RESOURCE_ENTRIES(X) \
    X(EXEMPT_ROLES) \
    X(EXEMPT_CHANNELS) \
    X(EMOJIS) \
    X(STICKERS) \
    X(THREADS) \
    X(MEMBERS) \
    X(MEMBER) \
    X(GUILDS) \
    X(ADDED_MEMBERS) \
    X(SOUNDBOARD_SOUNDS) \
    X(GUILD_SCHEDULED_EVENTS) \
    X(PRESENCES) \
    X(STAGE_INSTANCES)

#endif
