#ifndef DCC_JSON_KEY_ID_INTERACTION_ENTRIES_H
#define DCC_JSON_KEY_ID_INTERACTION_ENTRIES_H

#define DCC_JSON_KEY_ID_INTERACTION_ENTRIES(X) \
    X(ACTION) \
    X(INVITER) \
    X(DATA) \
    X(COMPONENT) \
    X(COMPONENTS) \
    X(ACCESSORY) \
    X(ITEMS) \
    X(MEDIA) \
    X(FILE) \
    X(STYLE) \
    X(CUSTOM_ID) \
    X(COMPONENT_TYPE) \
    X(VALUES) \
    X(OPTIONS) \
    X(DEFAULT_VALUES) \
    X(CHANNEL_TYPES) \
    X(VALUE) \
    X(LABEL) \
    X(PLACEHOLDER) \
    X(DISABLED) \
    X(REQUIRED) \
    X(DEFAULT) \
    X(DIVIDER) \
    X(SPACING) \
    X(MIN_VALUES) \
    X(MAX_VALUES) \
    X(MIN_LENGTH) \
    X(MAX_LENGTH) \
    X(ACCENT_COLOR) \
    X(SPOILER) \
    X(FOCUSED) \
    X(LOCALE) \
    X(GUILD_LOCALE) \
    X(APP_PERMISSIONS) \
    X(ATTACHMENT_SIZE_LIMIT) \
    X(VERSION) \
    X(CONTEXT) \
    X(AUTHORIZING_INTEGRATION_OWNERS) \
    X(ENTITLEMENTS) \
    X(USERS) \
    X(MESSAGES) \
    X(ATTACHMENTS) \
    X(RESOLVED) \
    X(SIZE) \
    X(FILENAME) \
    X(PROXY_URL) \
    X(CONTENT_TYPE) \
    X(EPHEMERAL) \
    X(DURATION_SECS) \
    X(WAVEFORM)

#endif
