#ifndef DCC_JSON_KEY_ID_COLLECTION_TIME_ENTRIES_H
#define DCC_JSON_KEY_ID_COLLECTION_TIME_ENTRIES_H

#define DCC_JSON_KEY_ID_COLLECTION_TIME_ENTRIES(X) \
    X(SKU_IDS) \
    X(ENTITLEMENT_IDS) \
    X(STARTS_AT) \
    X(ENDS_AT) \
    X(CURRENT_PERIOD_START) \
    X(CURRENT_PERIOD_END) \
    X(CANCELED_AT) \
    X(SINCE)

#endif
