#ifndef DCC_JSON_KEY_ID_CORE_GATEWAY_ENTRIES_H
#define DCC_JSON_KEY_ID_CORE_GATEWAY_ENTRIES_H

#define DCC_JSON_KEY_ID_CORE_GATEWAY_ENTRIES(X) \
    X(OP) \
    X(S) \
    X(T) \
    X(D) \
    X(HEARTBEAT_INTERVAL) \
    X(SESSION_ID) \
    X(RESUME_GATEWAY_URL)

#endif
