#ifndef DCC_JSON_KEY_ID_CORE_MESSAGE_ENTRIES_H
#define DCC_JSON_KEY_ID_CORE_MESSAGE_ENTRIES_H

#define DCC_JSON_KEY_ID_CORE_MESSAGE_ENTRIES(X) \
    X(ID) \
    X(CHANNEL_ID) \
    X(GUILD_ID) \
    X(CONTENT) \
    X(TTS) \
    X(MENTION_EVERYONE) \
    X(PINNED) \
    X(WEBHOOK_ID) \
    X(EDITED_TIMESTAMP) \
    X(FLAGS) \
    X(PUBLIC_FLAGS) \
    X(AUTHOR)

#endif
