#ifndef DCC_JSON_KEY_ID_COLLECTION_ACTIVITY_ENTRIES_H
#define DCC_JSON_KEY_ID_COLLECTION_ACTIVITY_ENTRIES_H

#define DCC_JSON_KEY_ID_COLLECTION_ACTIVITY_ENTRIES(X) \
    X(URL) \
    X(STATE) \
    X(DETAILS) \
    X(ACTIVITIES)

#endif
