#ifndef DCC_JSON_KEY_ID_RESOURCE_VOICE_ENTRIES_H
#define DCC_JSON_KEY_ID_RESOURCE_VOICE_ENTRIES_H

#define DCC_JSON_KEY_ID_RESOURCE_VOICE_ENTRIES(X) \
    X(USER_ID) \
    X(DEAF) \
    X(MUTE) \
    X(SELF_DEAF) \
    X(SELF_MUTE) \
    X(SELF_STREAM) \
    X(SELF_VIDEO) \
    X(SUPPRESS)

#endif
