#ifndef DCC_JSON_KEY_ID_GUILD_ENTRIES_H
#define DCC_JSON_KEY_ID_GUILD_ENTRIES_H

#define DCC_JSON_KEY_ID_GUILD_ENTRIES(X) \
    X(NICK) \
    X(ICON) \
    X(AVATAR) \
    X(BANNER) \
    X(VANITY_URL_CODE) \
    X(PREFERRED_LOCALE) \
    X(SPLASH) \
    X(DISCOVERY_SPLASH) \
    X(NONCE) \
    X(AFK_CHANNEL_ID) \
    X(SYSTEM_CHANNEL_ID) \
    X(RULES_CHANNEL_ID) \
    X(PUBLIC_UPDATES_CHANNEL_ID) \
    X(WIDGET_CHANNEL_ID) \
    X(SAFETY_ALERTS_CHANNEL_ID) \
    X(AFK_TIMEOUT) \
    X(MAX_PRESENCES) \
    X(MAX_MEMBERS) \
    X(PREMIUM_SUBSCRIPTION_COUNT) \
    X(MAX_VIDEO_CHANNEL_USERS) \
    X(DEFAULT_MESSAGE_NOTIFICATIONS) \
    X(PREMIUM_TIER) \
    X(VERIFICATION_LEVEL) \
    X(EXPLICIT_CONTENT_FILTER) \
    X(MFA_LEVEL) \
    X(NSFW_LEVEL) \
    X(WIDGET_ENABLED) \
    X(PREMIUM_PROGRESS_BAR_ENABLED) \
    X(VOICE_START_TIME)

#endif
