#ifndef DCC_JSON_KEY_ID_CORE_USER_RESOURCE_ENTRIES_H
#define DCC_JSON_KEY_ID_CORE_USER_RESOURCE_ENTRIES_H

#define DCC_JSON_KEY_ID_CORE_USER_RESOURCE_ENTRIES(X) \
    X(USERNAME) \
    X(GLOBAL_NAME) \
    X(DISCRIMINATOR) \
    X(BOT) \
    X(NAME) \
    X(UNAVAILABLE) \
    X(LARGE) \
    X(MEMBER_COUNT) \
    X(APPLICATION_ID) \
    X(TYPE) \
    X(TOKEN) \
    X(USER) \
    X(ROLE)

#endif
