#ifndef DCC_JSON_GATEWAY_PAYLOAD_INTERACTION_RESOLVED_USER_STATE_H
#define DCC_JSON_GATEWAY_PAYLOAD_INTERACTION_RESOLVED_USER_STATE_H

#define DCC_JSON_GATEWAY_PAYLOAD_INTERACTION_RESOLVED_USER_FIELDS \
    dcc_user_t interaction_resolved_users[DCC_JSON_GATEWAY_INTERACTION_RESOLVED_CAP]; \
    char interaction_resolved_usernames[DCC_JSON_GATEWAY_INTERACTION_RESOLVED_CAP][128]; \
    char interaction_resolved_user_global_names[DCC_JSON_GATEWAY_INTERACTION_RESOLVED_CAP][128]; \
    char interaction_resolved_user_avatars[DCC_JSON_GATEWAY_INTERACTION_RESOLVED_CAP][128]

#endif
