#ifndef DCC_JSON_KEY_ID_RESOURCE_REFERENCE_ENTRIES_H
#define DCC_JSON_KEY_ID_RESOURCE_REFERENCE_ENTRIES_H

#define DCC_JSON_KEY_ID_RESOURCE_REFERENCE_ENTRIES(X) \
    X(MESSAGE_ID) \
    X(ROLE_ID) \
    X(PARENT_ID) \
    X(TARGET_ID) \
    X(SKU_ID) \
    X(ENTITLEMENT_ID) \
    X(SUBSCRIPTION_ID) \
    X(PROMOTION_ID) \
    X(GIFT_CODE_FLAGS) \
    X(GUILD_SCHEDULED_EVENT_ID)

#endif
