#ifndef DCC_JSON_KEY_ID_COLLECTION_CLIENT_ENTRIES_H
#define DCC_JSON_KEY_ID_COLLECTION_CLIENT_ENTRIES_H

#define DCC_JSON_KEY_ID_COLLECTION_CLIENT_ENTRIES(X) \
    X(CLIENT_STATUS) \
    X(DESKTOP) \
    X(MOBILE) \
    X(WEB) \
    X(JOIN_TIMESTAMP)

#endif
