#ifndef DCC_JSON_KEY_ID_RESOURCE_SCALAR_ENTRIES_H
#define DCC_JSON_KEY_ID_RESOURCE_SCALAR_ENTRIES_H

#define DCC_JSON_KEY_ID_RESOURCE_SCALAR_ENTRIES(X) \
    X(EMOJI) \
    X(COUNT) \
    X(ACTION_TYPE) \
    X(TRIGGER_TYPE) \
    X(RULE_TRIGGER_TYPE) \
    X(TARGET_TYPE) \
    X(CHANNEL_TYPE) \
    X(ANSWER_ID) \
    X(ANIMATION_TYPE) \
    X(OPCODE) \
    X(RETRY_AFTER) \
    X(MAX_AGE) \
    X(MAX_USES) \
    X(USES) \
    X(PRIVACY_LEVEL) \
    X(ENTITY_TYPE) \
    X(VOLUME) \
    X(AVAILABLE) \
    X(PENDING) \
    X(TEMPORARY) \
    X(BURST) \
    X(NEWLY_CREATED) \
    X(CHUNK_INDEX) \
    X(CHUNK_COUNT)

#endif
