#ifndef DCC_JSON_KEY_ID_COLLECTION_TEXT_ENTRIES_H
#define DCC_JSON_KEY_ID_COLLECTION_TEXT_ENTRIES_H

#define DCC_JSON_KEY_ID_COLLECTION_TEXT_ENTRIES(X) \
    X(EMOJI_NAME) \
    X(MATCHED_KEYWORD) \
    X(MATCHED_CONTENT) \
    X(TOPIC) \
    X(EVENT_TYPE) \
    X(ENABLED) \
    X(DISCOVERABLE_DISABLED)

#endif
