#ifndef DCC_JSON_KEY_ID_RESOURCE_TEXT_TIME_ENTRIES_H
#define DCC_JSON_KEY_ID_RESOURCE_TEXT_TIME_ENTRIES_H

#define DCC_JSON_KEY_ID_RESOURCE_TEXT_TIME_ENTRIES(X) \
    X(CODE) \
    X(REASON) \
    X(STATUS) \
    X(ENDPOINT) \
    X(TIMESTAMP) \
    X(CREATED_AT) \
    X(EXPIRES_AT) \
    X(LAST_PIN_TIMESTAMP) \
    X(SCHEDULED_START_TIME) \
    X(SCHEDULED_END_TIME) \
    X(USER_COUNT) \
    X(JOINED_AT) \
    X(PREMIUM_SINCE) \
    X(COMMUNICATION_DISABLED_UNTIL) \
    X(REQUEST_TO_SPEAK_TIMESTAMP)

#endif
